import { NodeType } from '@stoplight/types';
import { IContentsNodeWithId, IProjectNode } from '../../types';

export const nodes: IProjectNode[] = [
  {
    id: 'gzv028oc',
    type: NodeType.Article,
    name: 'UI Overview',
    srn: 'gh/stoplightio/studio/docs/ui-overview.md',
  },
  {
    id: 'ks8cwyvs',
    type: NodeType.Article,
    name: 'Modeling Introduction',
    srn: 'gh/stoplightio/studio/docs/designing-apis/10-getting-started.md',
  },
  {
    id: 'vxeympcn',
    type: NodeType.Article,
    name: 'Project Structure (Design & Modeling)',
    srn: 'gh/stoplightio/studio/docs/designing-apis/directory-structure.md',
  },
  {
    id: 'ovxlx772',
    type: NodeType.Article,
    name: 'Using References',
    srn: 'gh/stoplightio/studio/docs/designing-apis/using-references.md',
  },
  {
    id: 'bb4i9mek',
    type: NodeType.Article,
    name: 'Working with Models',
    srn: 'gh/stoplightio/studio/docs/designing-apis/http-endpoints.md',
  },
  {
    id: 'c2riagde',
    type: NodeType.Article,
    name: 'Validation and Linting',
    srn: 'gh/stoplightio/studio/docs/designing-apis/validation-style-guide.md',
  },
  {
    id: 'lnciknzw',
    type: NodeType.Article,
    name: 'Documentation Quickstart Guide',
    srn: 'gh/stoplightio/studio/docs/writing-tech-docs/10-getting-started.md',
  },
  {
    id: '20p2qlve',
    type: NodeType.Article,
    name: 'Publishing in Studio',
    srn: 'gh/stoplightio/studio/docs/writing-tech-docs/publishing.md',
  },
  {
    id: 'stz6uwdt',
    type: NodeType.Article,
    name: 'Using Images',
    srn: 'gh/stoplightio/studio/docs/writing-tech-docs/using-images.md',
  },
  {
    id: 't6694f4v',
    type: NodeType.Article,
    name: 'Directory Structure (Documentation)',
    srn: 'gh/stoplightio/studio/docs/writing-tech-docs/directory-structure.md',
  },
  {
    id: '4znkyjxn',
    type: NodeType.Article,
    name: 'Linking Between Articles',
    srn: 'gh/stoplightio/studio/docs/writing-tech-docs/linking-between-articles.md',
  },
  {
    id: 'cu1rik0j',
    type: NodeType.Article,
    name: 'Using Markdown in Documentation',
    srn: 'gh/stoplightio/studio/docs/writing-tech-docs/stoplight-flavored-markdown.md',
  },
  {
    id: 'yok9mcyg',
    type: NodeType.Article,
    name: 'Customize Interface Panels',
    srn: 'gh/stoplightio/studio/docs/workflow/customize-interface.md',
  },
  {
    id: 'kfc8upgh',
    type: NodeType.Article,
    name: 'Working with an Existing Project',
    srn: 'gh/stoplightio/studio/docs/workflow/working-with-existing-project.md',
  },
  {
    id: '3rxli9io',
    type: NodeType.Article,
    name: 'Working with Files',
    srn: 'gh/stoplightio/studio/docs/workflow/working-with-files.md',
  },
  {
    id: 'rb6z0v9w',
    type: NodeType.Article,
    name: 'Working with Git',
    srn: 'gh/stoplightio/studio/docs/workflow/working-with-git.md',
  },
  {
    id: 'readme',
    type: NodeType.Article,
    name: 'Studio Docs',
    srn: 'gh/stoplightio/studio/README.md',
  },
];

export const contents: IContentsNodeWithId[] = [
  {
    id: 'readme',
    name: 'Studio Docs',
    depth: 0,
    type: 'item',
    icon: 'document',
    href: 'gh/stoplightio/studio/README.md',
  },
  {
    id: 'gzv028oc',
    name: 'UI Overview',
    depth: 0,
    type: 'item',
    icon: 'document',
    href: 'gh/stoplightio/studio/docs/ui-overview.md',
  },
  {
    id: '0-0',
    name: 'Designing Apis',
    depth: 0,
    type: 'group',
    icon: 'folder-close',
  },
  {
    id: 'ks8cwyvs',
    name: 'Modeling Introduction',
    depth: 1,
    type: 'item',
    icon: 'document',
    href: 'gh/stoplightio/studio/docs/designing-apis/10-getting-started.md',
  },
  {
    id: 'vxeympcn',
    name: 'Project Structure (Design & Modeling)',
    depth: 1,
    type: 'item',
    icon: 'document',
    href: 'gh/stoplightio/studio/docs/designing-apis/directory-structure.md',
  },
  {
    id: 'bb4i9mek',
    name: 'Working with Models',
    depth: 1,
    type: 'item',
    icon: 'document',
    href: 'gh/stoplightio/studio/docs/designing-apis/http-endpoints.md',
  },
  {
    id: 'ovxlx772',
    name: 'Using References',
    depth: 1,
    type: 'item',
    icon: 'document',
    href: 'gh/stoplightio/studio/docs/designing-apis/using-references.md',
  },
  {
    id: 'c2riagde',
    name: 'Validation and Linting',
    depth: 1,
    type: 'item',
    icon: 'document',
    href: 'gh/stoplightio/studio/docs/designing-apis/validation-style-guide.md',
  },
  {
    id: '6-0',
    name: 'Workflow',
    depth: 0,
    type: 'group',
    icon: 'folder-close',
  },
  {
    id: 'yok9mcyg',
    name: 'Customize Interface Panels',
    depth: 1,
    type: 'item',
    icon: 'document',
    href: 'gh/stoplightio/studio/docs/workflow/customize-interface.md',
  },
  {
    id: 'kfc8upgh',
    name: 'Working with an Existing Project',
    depth: 1,
    type: 'item',
    icon: 'document',
    href: 'gh/stoplightio/studio/docs/workflow/working-with-existing-project.md',
  },
  {
    id: '3rxli9io',
    name: 'Working with Files',
    depth: 1,
    type: 'item',
    icon: 'document',
    href: 'gh/stoplightio/studio/docs/workflow/working-with-files.md',
  },
  {
    id: 'rb6z0v9w',
    name: 'Working with Git',
    depth: 1,
    type: 'item',
    icon: 'document',
    href: 'gh/stoplightio/studio/docs/workflow/working-with-git.md',
  },
  {
    id: '10-0',
    name: 'Writing Tech Docs',
    depth: 0,
    type: 'group',
    icon: 'folder-close',
  },
  {
    id: 'lnciknzw',
    name: 'Documentation Quickstart Guide',
    depth: 1,
    type: 'item',
    icon: 'document',
    href: 'gh/stoplightio/studio/docs/writing-tech-docs/10-getting-started.md',
  },
  {
    id: 't6694f4v',
    name: 'Directory Structure (Documentation)',
    depth: 1,
    type: 'item',
    icon: 'document',
    href: 'gh/stoplightio/studio/docs/writing-tech-docs/directory-structure.md',
  },
  {
    id: '4znkyjxn',
    name: 'Linking Between Articles',
    depth: 1,
    type: 'item',
    icon: 'document',
    href: 'gh/stoplightio/studio/docs/writing-tech-docs/linking-between-articles.md',
  },
  {
    id: '20p2qlve',
    name: 'Publishing in Studio',
    depth: 1,
    type: 'item',
    icon: 'document',
    href: 'gh/stoplightio/studio/docs/writing-tech-docs/publishing.md',
  },
  {
    id: 'cu1rik0j',
    name: 'Using Markdown in Documentation',
    depth: 1,
    type: 'item',
    icon: 'document',
    href: 'gh/stoplightio/studio/docs/writing-tech-docs/stoplight-flavored-markdown.md',
  },
  {
    id: 'stz6uwdt',
    name: 'Using Images',
    depth: 1,
    type: 'item',
    icon: 'document',
    href: 'gh/stoplightio/studio/docs/writing-tech-docs/using-images.md',
  },
];

export const nodeTypeIcons: IContentsNodeWithId[] = [
  {
    id: 'readme',
    name: 'Studio Docs',
    depth: 0,
    type: 'item',
    icon: 'cube',
    href: 'gh/stoplightio/studio/README.md',
  },
  {
    id: 'gzv028oc',
    name: 'UI Overview',
    depth: 0,
    type: 'item',
    icon: 'cube',
    href: 'gh/stoplightio/studio/docs/ui-overview.md',
  },
  {
    id: '0-0',
    name: 'Designing Apis',
    depth: 0,
    type: 'group',
  },
  {
    id: 'ks8cwyvs',
    name: 'Modeling Introduction',
    depth: 1,
    type: 'item',
    icon: 'cube',
    href: 'gh/stoplightio/studio/docs/designing-apis/10-getting-started.md',
  },
  {
    id: 'vxeympcn',
    name: 'Project Structure (Design & Modeling)',
    depth: 1,
    type: 'item',
    icon: 'cube',
    href: 'gh/stoplightio/studio/docs/designing-apis/directory-structure.md',
  },
  {
    id: 'bb4i9mek',
    name: 'Working with Models',
    depth: 1,
    type: 'item',
    icon: 'cube',
    href: 'gh/stoplightio/studio/docs/designing-apis/http-endpoints.md',
  },
  {
    id: 'ovxlx772',
    name: 'Using References',
    depth: 1,
    type: 'item',
    icon: 'cube',
    href: 'gh/stoplightio/studio/docs/designing-apis/using-references.md',
  },
  {
    id: 'c2riagde',
    name: 'Validation and Linting',
    depth: 1,
    type: 'item',
    icon: 'cube',
    href: 'gh/stoplightio/studio/docs/designing-apis/validation-style-guide.md',
  },
  {
    id: '6-0',
    name: 'Workflow',
    depth: 0,
    type: 'group',
  },
  {
    id: 'yok9mcyg',
    name: 'Customize Interface Panels',
    depth: 1,
    type: 'item',
    icon: 'cube',
    href: 'gh/stoplightio/studio/docs/workflow/customize-interface.md',
  },
  {
    id: 'kfc8upgh',
    name: 'Working with an Existing Project',
    depth: 1,
    type: 'item',
    icon: 'cube',
    href: 'gh/stoplightio/studio/docs/workflow/working-with-existing-project.md',
  },
  {
    id: '3rxli9io',
    name: 'Working with Files',
    depth: 1,
    type: 'item',
    icon: 'cube',
    href: 'gh/stoplightio/studio/docs/workflow/working-with-files.md',
  },
  {
    id: 'rb6z0v9w',
    name: 'Working with Git',
    depth: 1,
    type: 'item',
    icon: 'cube',
    href: 'gh/stoplightio/studio/docs/workflow/working-with-git.md',
  },
  {
    id: '10-0',
    name: 'Writing Tech Docs',
    depth: 0,
    type: 'group',
  },
  {
    id: 'lnciknzw',
    name: 'Documentation Quickstart Guide',
    depth: 1,
    type: 'item',
    icon: 'cube',
    href: 'gh/stoplightio/studio/docs/writing-tech-docs/10-getting-started.md',
  },
  {
    id: 't6694f4v',
    name: 'Directory Structure (Documentation)',
    depth: 1,
    type: 'item',
    icon: 'cube',
    href: 'gh/stoplightio/studio/docs/writing-tech-docs/directory-structure.md',
  },
  {
    id: '4znkyjxn',
    name: 'Linking Between Articles',
    depth: 1,
    type: 'item',
    icon: 'cube',
    href: 'gh/stoplightio/studio/docs/writing-tech-docs/linking-between-articles.md',
  },
  {
    id: '20p2qlve',
    name: 'Publishing in Studio',
    depth: 1,
    type: 'item',
    icon: 'cube',
    href: 'gh/stoplightio/studio/docs/writing-tech-docs/publishing.md',
  },
  {
    id: 'cu1rik0j',
    name: 'Using Markdown in Documentation',
    depth: 1,
    type: 'item',
    icon: 'cube',
    href: 'gh/stoplightio/studio/docs/writing-tech-docs/stoplight-flavored-markdown.md',
  },
  {
    id: 'stz6uwdt',
    name: 'Using Images',
    depth: 1,
    type: 'item',
    icon: 'cube',
    href: 'gh/stoplightio/studio/docs/writing-tech-docs/using-images.md',
  },
];
