version: 1

update_configs:
  - package_manager: 'javascript'
    directory: '/'
    update_schedule: 'live'

    commit_message:
      prefix: 'fix'
      prefix_development: 'chore'
      include_scope: true

    allowed_updates:
      - match:
          update_type: 'security'
      - match:
          dependency_name: '@stoplight/*'

    automerged_updates:
      - match:
          dependency_name: '@stoplight/*'
          update_type: 'semver:minor'
