version: 1

update_configs:

  - package_manager: 'javascript'
    directory: '/'
    target_branch: main
    update_schedule: 'live'
    version_requirement_updates: 'increase_versions'

    commit_message:
      prefix: 'fix'
      prefix_development: 'fix'
      include_scope: true

    allowed_updates:
      - match:
          update_type: 'security'
          
  - package_manager: 'javascript'
    directory: '/'
    target_branch: v6
    update_schedule: 'live'
    version_requirement_updates: 'increase_versions'

    commit_message:
      prefix: 'fix'
      prefix_development: 'fix'
      include_scope: true

    allowed_updates:
      - match:
          update_type: 'security'
