import { INodeGraph } from '../../../types';

export const graph: INodeGraph = {
  nodes: [
    {
      depth: 1,
      groupNodeId: 34358,
      type: 'model',
      name: 'Account',
      uri: '/Account/Account.v1.yaml',
      version: '1',
      groupSlug: 'master',
      projectName: 'sample-models',
      srn: 'gh/stoplightio/sample-models/Account/Account.v1.yaml',
    },
    {
      depth: 1,
      groupNodeId: 34372,
      type: 'model',
      name: 'AirportTransferOffer_Company',
      uri: '/AirportTransferOffer/AirportTransferOffer_Company.v1.yaml',
      version: '1',
      groupSlug: 'master',
      projectName: 'sample-models',
      srn: 'gh/stoplightio/sample-models/AirportTransferOffer/AirportTransferOffer_Company.v1.yaml',
    },
    {
      depth: 1,
      groupNodeId: 34373,
      type: 'model',
      name: 'AirportTransferOffer_Location',
      uri: '/AirportTransferOffer/AirportTransferOffer_Location.v1.yaml',
      version: '1',
      groupSlug: 'master',
      projectName: 'sample-models',
      srn: 'gh/stoplightio/sample-models/AirportTransferOffer/AirportTransferOffer_Location.v1.yaml',
    },
    {
      depth: 1,
      groupNodeId: 34418,
      type: 'model',
      name: 'DCSPassenger',
      uri: '/DCSPassenger/DCSPassenger.v1.yaml',
      version: '1',
      groupSlug: 'master',
      projectName: 'sample-models',
      srn: 'gh/stoplightio/sample-models/DCSPassenger/DCSPassenger.v1.yaml',
    },
    {
      depth: 1,
      groupNodeId: 34498,
      type: 'model',
      name: 'PNRModel',
      uri: '/PNRModel/PNRModel.v2.yaml',
      version: '2',
      groupSlug: 'master',
      projectName: 'sample-models',
      srn: 'gh/stoplightio/sample-models/PNRModel/PNRModel.v2.yaml',
    },
    {
      depth: 1,
      groupNodeId: 34532,
      type: 'model',
      name: 'SecurityOrganization',
      uri: '/SecurityOrganization/SecurityOrganization.v1.yaml',
      version: '1',
      groupSlug: 'master',
      projectName: 'sample-models',
      srn: 'gh/stoplightio/sample-models/SecurityOrganization/SecurityOrganization.v1.yaml',
    },
    {
      depth: 1,
      groupNodeId: 34536,
      type: 'model',
      name: 'SecurityUser',
      uri: '/SecurityUser/SecurityUser.v1.yaml',
      version: '1',
      groupSlug: 'master',
      projectName: 'sample-models',
      srn: 'gh/stoplightio/sample-models/SecurityUser/SecurityUser.v1.yaml',
    },
    {
      depth: 2,
      groupNodeId: 34371,
      type: 'model',
      name: 'AirportTransferOffer',
      uri: '/AirportTransferOffer/AirportTransferOffer.v1.yaml',
      version: '1',
      groupSlug: 'master',
      projectName: 'sample-models',
      srn: 'gh/stoplightio/sample-models/AirportTransferOffer/AirportTransferOffer.v1.yaml',
    },
    {
      depth: 2,
      groupNodeId: 34479,
      type: 'model',
      name: 'HierarchyNode',
      uri: '/HierarchyNode/HierarchyNode.v1.yaml',
      version: '1',
      groupSlug: 'master',
      projectName: 'sample-models',
      srn: 'gh/stoplightio/sample-models/HierarchyNode/HierarchyNode.v1.yaml',
    },
    {
      depth: 2,
      groupNodeId: 34526,
      type: 'model',
      name: 'SecurityConsumer',
      uri: '/SecurityConsumer/SecurityConsumer.v1.yaml',
      version: '1',
      groupSlug: 'master',
      projectName: 'sample-models',
      srn: 'gh/stoplightio/sample-models/SecurityConsumer/SecurityConsumer.v1.yaml',
    },
    {
      depth: 2,
      groupNodeId: 34533,
      type: 'model',
      name: 'SecurityOrganizationUnit',
      uri: '/SecurityOrganizationUnit/SecurityOrganizationUnit.v1.yaml',
      version: '1',
      groupSlug: 'master',
      projectName: 'sample-models',
      srn: 'gh/stoplightio/sample-models/SecurityOrganizationUnit/SecurityOrganizationUnit.v1.yaml',
    },
    {
      depth: 2,
      groupNodeId: 34565,
      type: 'model',
      name: 'User',
      uri: '/User/User.v2.yaml',
      version: '2',
      groupSlug: 'master',
      projectName: 'sample-models',
      srn: 'gh/stoplightio/sample-models/User/User.v2.yaml',
    },
    {
      depth: 3,
      groupNodeId: 34457,
      type: 'model',
      name: 'EventLog',
      uri: '/EventLog/EventLog.v2.yaml',
      version: '2',
      groupSlug: 'master',
      projectName: 'sample-models',
      srn: 'gh/stoplightio/sample-models/EventLog/EventLog.v2.yaml',
    },
    {
      depth: 3,
      groupNodeId: 34359,
      type: 'model',
      name: 'AclAssignment',
      uri: '/AclAssignment/AclAssignment.v1.yaml',
      version: '1',
      groupSlug: 'master',
      projectName: 'sample-models',
      srn: 'gh/stoplightio/sample-models/AclAssignment/AclAssignment.v1.yaml',
    },
    {
      depth: 3,
      groupNodeId: 34535,
      type: 'model',
      name: 'SecurityRoleAssignment',
      uri: '/SecurityRoleAssignement/SecurityRoleAssignment.v1.yaml',
      version: '1',
      groupSlug: 'master',
      projectName: 'sample-models',
      srn: 'gh/stoplightio/sample-models/SecurityRoleAssignement/SecurityRoleAssignment.v1.yaml',
    },
    {
      depth: 4,
      groupNodeId: 34447,
      type: 'model',
      name: 'DigitalFingerprint',
      uri: '/DigitalFingerprint/DigitalFingerprint.v1.yaml',
      version: '1',
      groupSlug: 'master',
      projectName: 'sample-models',
      srn: 'gh/stoplightio/sample-models/DigitalFingerprint/DigitalFingerprint.v1.yaml',
    },
    {
      depth: 4,
      groupNodeId: 34531,
      type: 'model',
      name: 'SecurityLocation',
      uri: '/SecurityLocation/SecurityLocation.v1.yaml',
      version: '1',
      groupSlug: 'master',
      projectName: 'sample-models',
      srn: 'gh/stoplightio/sample-models/SecurityLocation/SecurityLocation.v1.yaml',
    },
  ],
  edges: [
    {
      fromGroupNodeId: 34358,
      fromPath: '#/definitions/Account_Actor/properties/contact',
      toGroupNodeId: 34412,
      toPath: '#/',
    },
    { fromGroupNodeId: 34372, fromPath: '#/properties/contact', toGroupNodeId: 34412, toPath: '#/' },
    { fromGroupNodeId: 34373, fromPath: '#/properties/contact', toGroupNodeId: 34412, toPath: '#/' },
    {
      fromGroupNodeId: 34418,
      fromPath: '#/definitions/DCSPassengerData/properties/contacts/items',
      toGroupNodeId: 34412,
      toPath: '#/',
    },
    { fromGroupNodeId: 34498, fromPath: '#/properties/contacts/items', toGroupNodeId: 34412, toPath: '#/' },
    { fromGroupNodeId: 34532, fromPath: '#/properties/adminContacts/items', toGroupNodeId: 34412, toPath: '#/' },
    { fromGroupNodeId: 34536, fromPath: '#/properties/contact', toGroupNodeId: 34412, toPath: '#/' },
    {
      fromGroupNodeId: 34358,
      fromPath: '#/properties/actor',
      toGroupNodeId: 34358,
      toPath: '#/definitions/Account_Actor',
    },
    {
      fromGroupNodeId: 34358,
      fromPath: '#/properties/authentication/items',
      toGroupNodeId: 34358,
      toPath: '#/definitions/Account_Authentication',
    },
    { fromGroupNodeId: 34371, fromPath: '#/properties/company', toGroupNodeId: 34372, toPath: '#/' },
    { fromGroupNodeId: 34371, fromPath: '#/properties/dropOff', toGroupNodeId: 34373, toPath: '#/' },
    { fromGroupNodeId: 34371, fromPath: '#/properties/pickUp', toGroupNodeId: 34373, toPath: '#/' },
    { fromGroupNodeId: 34418, fromPath: '#/allOf/0', toGroupNodeId: 34418, toPath: '#/definitions/DCSPassengerData' },
    {
      fromGroupNodeId: 34498,
      fromPath: '#/properties/group',
      toGroupNodeId: 34498,
      toPath: '#/definitions/TravelersGroup',
    },
    {
      fromGroupNodeId: 34498,
      fromPath: '#/properties/pnrProperties/items',
      toGroupNodeId: 34498,
      toPath: '#/definitions/PnrHeaderFlag',
    },
    { fromGroupNodeId: 34479, fromPath: '#/properties/organization', toGroupNodeId: 34532, toPath: '#/' },
    { fromGroupNodeId: 34526, fromPath: '#/properties/organization', toGroupNodeId: 34532, toPath: '#/' },
    { fromGroupNodeId: 34533, fromPath: '#/properties/owner', toGroupNodeId: 34532, toPath: '#/' },
    { fromGroupNodeId: 34526, fromPath: '#/properties/user', toGroupNodeId: 34536, toPath: '#/' },
    {
      fromGroupNodeId: 34565,
      fromPath: '#/properties/credentials/properties/amadeusCredentials',
      toGroupNodeId: 34536,
      toPath: '#/',
    },
    { fromGroupNodeId: 34536, fromPath: '#/properties/administrationHome', toGroupNodeId: 34479, toPath: '#/' },
    { fromGroupNodeId: 34536, fromPath: '#/properties/authenticationHome', toGroupNodeId: 34479, toPath: '#/' },
    { fromGroupNodeId: 34457, fromPath: '#/properties/user', toGroupNodeId: 34565, toPath: '#/' },
    { fromGroupNodeId: 34359, fromPath: '#/properties/consumer', toGroupNodeId: 34526, toPath: '#/' },
    { fromGroupNodeId: 34535, fromPath: '#/properties/consumer', toGroupNodeId: 34526, toPath: '#/' },
    { fromGroupNodeId: 34359, fromPath: '#/properties/consumer', toGroupNodeId: 34526, toPath: '#/' },
    { fromGroupNodeId: 34535, fromPath: '#/properties/consumer', toGroupNodeId: 34526, toPath: '#/' },
    { fromGroupNodeId: 34479, fromPath: '#/properties/organizationUnit', toGroupNodeId: 34533, toPath: '#/' },
    { fromGroupNodeId: 34526, fromPath: '#/properties/organizationUnit', toGroupNodeId: 34533, toPath: '#/' },
    { fromGroupNodeId: 34359, fromPath: '#/properties/activationDate', toGroupNodeId: 34457, toPath: '#/' },
    { fromGroupNodeId: 34359, fromPath: '#/properties/expirationDate', toGroupNodeId: 34457, toPath: '#/' },
    { fromGroupNodeId: 34447, fromPath: '#/properties/creationDate', toGroupNodeId: 34457, toPath: '#/' },
    { fromGroupNodeId: 34447, fromPath: '#/properties/lastUseDate', toGroupNodeId: 34457, toPath: '#/' },
    {
      fromGroupNodeId: 34457,
      fromPath: '#/definitions/EventLog_HistoryChangeLog/allOf/0',
      toGroupNodeId: 34457,
      toPath: '#/definitions/EventLog_ChangeLog',
    },
    {
      fromGroupNodeId: 34457,
      fromPath: '#/definitions/EventLog_PatchOperation/allOf/0',
      toGroupNodeId: 34457,
      toPath: '#/definitions/EventLog_ChangeLog',
    },
    {
      fromGroupNodeId: 34457,
      fromPath: '#/properties/changeLog/items/allOf/0',
      toGroupNodeId: 34457,
      toPath: '#/definitions/EventLog_HistoryChangeLog',
    },
    {
      fromGroupNodeId: 34457,
      fromPath: '#/properties/changeLog/items/allOf/1',
      toGroupNodeId: 34457,
      toPath: '#/definitions/EventLog_PatchOperation',
    },
    { fromGroupNodeId: 34531, fromPath: '#/properties/lastSignInDate', toGroupNodeId: 34457, toPath: '#/' },
    { fromGroupNodeId: 34535, fromPath: '#/properties/activationDate', toGroupNodeId: 34457, toPath: '#/' },
    { fromGroupNodeId: 34535, fromPath: '#/properties/expirationDate', toGroupNodeId: 34457, toPath: '#/' },
    { fromGroupNodeId: 34536, fromPath: '#/properties/activationDate', toGroupNodeId: 34457, toPath: '#/' },
    { fromGroupNodeId: 34536, fromPath: '#/properties/creationDate', toGroupNodeId: 34457, toPath: '#/' },
    { fromGroupNodeId: 34536, fromPath: '#/properties/lastChangePasswordDate', toGroupNodeId: 34457, toPath: '#/' },
    { fromGroupNodeId: 34536, fromPath: '#/properties/lastSignInDate', toGroupNodeId: 34457, toPath: '#/' },
    { fromGroupNodeId: 34536, fromPath: '#/properties/administrationHome', toGroupNodeId: 34479, toPath: '#/' },
    { fromGroupNodeId: 34536, fromPath: '#/properties/authenticationHome', toGroupNodeId: 34479, toPath: '#/' },
    { fromGroupNodeId: 34359, fromPath: '#/properties/consumer', toGroupNodeId: 34526, toPath: '#/' },
    { fromGroupNodeId: 34535, fromPath: '#/properties/consumer', toGroupNodeId: 34526, toPath: '#/' },
    { fromGroupNodeId: 34526, fromPath: '#/properties/user', toGroupNodeId: 34536, toPath: '#/' },
    {
      fromGroupNodeId: 34565,
      fromPath: '#/properties/credentials/properties/amadeusCredentials',
      toGroupNodeId: 34536,
      toPath: '#/',
    },
    { fromGroupNodeId: 34536, fromPath: '#/properties/digital-fingerprints/items', toGroupNodeId: 34447, toPath: '#/' },
    { fromGroupNodeId: 34457, fromPath: '#/properties/user', toGroupNodeId: 34565, toPath: '#/' },
    { fromGroupNodeId: 34359, fromPath: '#/properties/consumer', toGroupNodeId: 34526, toPath: '#/' },
    { fromGroupNodeId: 34535, fromPath: '#/properties/consumer', toGroupNodeId: 34526, toPath: '#/' },
    { fromGroupNodeId: 34536, fromPath: '#/properties/locations/items', toGroupNodeId: 34531, toPath: '#/' },
    { fromGroupNodeId: 34526, fromPath: '#/properties/user', toGroupNodeId: 34536, toPath: '#/' },
    {
      fromGroupNodeId: 34565,
      fromPath: '#/properties/credentials/properties/amadeusCredentials',
      toGroupNodeId: 34536,
      toPath: '#/',
    },
  ],
};
