name: Jira Issue Label Added

# on:
#   issues:
#     types:
#       - labeled

on:
  workflow_dispatch:

jobs:
  call-workflow:
    uses: stoplightio/.github/.github/workflows/jira-issue-label-added.yaml@master
    with:
      team-name: "Bear Claws"
    secrets: inherit